spring:
  application:
    name: ingestion-test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
    url: jdbc:mariadb://localhost:3306/ingestion_test
    hikari:
      max-lifetime: 120000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081